# Generated by Django 5.2.7 on 2026-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tag', models.CharField(choices=[('Networking', 'Networking'), ('Cybersecurity', 'Cybersecurity'), ('Mobile', 'Mobile Apps'), ('Career', 'Career & IT Support'), ('Projects', 'Projects'), ('Mindset', 'Mindset')], default='Networking', max_length=50)),
                ('date_display', models.CharField(default='May 2026', max_length=50)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('summary', models.TextField()),
                ('content_json', models.JSONField(default=list, help_text="Structured article content as list of dicts: [{'type': 'paragraph'|'heading'|'quote'|'list', 'text': '...', 'items': [...]}]")),
                ('featured_image', models.CharField(default='banner-network.jpg', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('image', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Core Skill', max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('accent', models.CharField(default='var(--color-burgundy)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
