# Generated by Django 5.2.7 on 2026-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload photo from your device', null=True, upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload banner image from your device', null=True, upload_to='blog_banners/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload certificate image from your device', null=True, upload_to='cert_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload project screenshot/image from your device', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload skill image from your device', null=True, upload_to='skills_images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.CharField(blank=True, default='banner-network.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_json',
            field=models.JSONField(default=list, help_text='Structured article content as list or dict uploaded by admin.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.CharField(blank=True, default='banner-network.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
